version: "3.9"
services:
  frontend:
    build: ./frontend
    command: npm run dev
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - ./.env
    depends_on:
      - backend
      - centrifugo

  backend:
    build: ./backend
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port ${BACKEND_PORT}  --reload
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - ./.env
    depends_on:
      - centrifugo
      - mongo
      - cache
  
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:latest
    command: centrifugo --admin
    ports:
      - "${CENTRIFUGO_PORT}:${CENTRIFUGO_PORT}"
    environment:
      - CENTRIFUGO_PORT=${CENTRIFUGO_PORT}
      - CENTRIFUGO_SECRET=${CENTRIFUGO_SECRET_KEY}
      - CENTRIFUGO_ADMIN_PASSWORD=${CENTRIFUGO_ADMIN_PASSWORD}
      - CENTRIFUGO_ADMIN_SECRET=${CENTRIFUGO_ADMIN_SECRET}
      - CENTRIFUGO_API_KEY=${CENTRIFUGO_API_KEY}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
  
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/mongo/db
    env_file:
      - ./.env
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"

  cache:
    image: redis:latest
    restart: always
    command: redis-server --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes: 
      - cache_data:/redis/db
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

volumes:
  mongo_data:
    driver: local
  cache_data:
    driver: local